//** Amazon Auth Types */

export const LOADING_ALL_QUESTION = '  LOADING_ALL_QUESTION';
export const LOADED_ALL_QUESTION = 'LOADED_ALL_QUESTION';
export const LOADED_DRAWER_OPEN_AND_CLOSE = 'LOADED_DRAWER_OPEN_AND_CLOSE';
